import argparse
import os
import numpy as np
import sys
import math
import matplotlib
matplotlib.use('pdf')
matplotlib.rc('figure', figsize=(8, 5))
import matplotlib.pyplot as plt
import cPickle as pickle

from histogram import Histogram

parser = argparse.ArgumentParser(description='Plot histogram for all pickle file in \
        directory generated by hist_make.py')
parser.add_argument('--dir', type=str, nargs=1,
        help='Directory of pickle files, generated by hist_maker.py', required=True)

args = parser.parse_args()
directory = args.dir[0]:

for name in os.listdir(directory):
    print 'Processing: %s...' % (name)
    hist = pickle(open(os.pathjoin(directory, name), 'rb'))
